export interface StandardsSelection {jurisdiction:'EG';referenceIds:string[]}
export interface StandardsReference {id:string;publisher:'ASHRAE'|'SMACNA'|'NFPA';title:string;edition:string;sourceUrl:string;ruleEvidence:'metadata-only';applicability:string;addendaStatus:'unverified'}
const ashrae='https://www.ashrae.org/technical-resources/standards-and-guidelines/read-only-versions-of-ashrae-standards';
export const STANDARDS_REFERENCES:readonly StandardsReference[]=[
 {id:'ashrae-62.1-2025',publisher:'ASHRAE',title:'Ventilation for Acceptable Indoor Air Quality',edition:'2025',sourceUrl:ashrae,applicability:'Nonresidential spaces; excludes nontransient residential dwelling units',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'ashrae-62.1-2019',publisher:'ASHRAE',title:'Ventilation for Acceptable Indoor Air Quality',edition:'2019',sourceUrl:ashrae,applicability:'Nonresidential spaces; project applicability requires verification',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'ashrae-55-2023',publisher:'ASHRAE',title:'Thermal Environmental Conditions for Human Occupancy',edition:'2023',sourceUrl:ashrae,applicability:'Thermal environment, activity and clothing; not temperature alone',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'ashrae-90.1-2025',publisher:'ASHRAE',title:'Energy Standard for Sites and Buildings Except Low-Rise Residential Buildings',edition:'2025',sourceUrl:'https://www.ashrae.org/technical-resources/bookstore/standard-90-1',applicability:'Energy efficiency except low-rise residential',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'smacna-duct-construction-4',publisher:'SMACNA',title:'HVAC Duct Construction Standards — Metal and Flexible',edition:'4th edition',sourceUrl:'https://www.smacna.org/technical-standards',applicability:'Metal and flexible duct construction; pressure class and manufacturer listing required',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'smacna-duct-design-5-2023',publisher:'SMACNA',title:'HVAC Systems Duct Design',edition:'5th edition (2023)',sourceUrl:'https://www.smacna.org/news/products-and-services-guide',applicability:'Duct and fan design; numerical criteria require manual evidence',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'nfpa-90a-2024',publisher:'NFPA',title:'Standard for the Installation of Air-Conditioning and Ventilating Systems',edition:'2024',sourceUrl:'https://www.nfpa.org/product/nfpa-90a-standard/p0090acode',applicability:'Applicable systems and fire/smoke conditions require edition-specific review',ruleEvidence:'metadata-only',addendaStatus:'unverified'},
 {id:'nfpa-90a-2027',publisher:'NFPA',title:'Standard for the Installation of Air-Conditioning and Ventilating Systems',edition:'2027',sourceUrl:'https://www.nfpa.org/product/nfpa-90a-standard/p0090acode',applicability:'Publisher-listed edition; not assumed adopted in Egypt',ruleEvidence:'metadata-only',addendaStatus:'unverified'}
];
export const DEFAULT_STANDARDS_SELECTION:StandardsSelection={jurisdiction:'EG',referenceIds:['ashrae-62.1-2025','ashrae-55-2023','ashrae-90.1-2025','smacna-duct-construction-4','smacna-duct-design-5-2023','nfpa-90a-2024']};
export function resolveStandardsSelection(selection:StandardsSelection=DEFAULT_STANDARDS_SELECTION):{jurisdiction:'EG';references:StandardsReference[];issueReady:false;unresolved:string[]} {
 if(selection.jurisdiction!=='EG')throw new Error('Unsupported jurisdiction.');
 if(!Array.isArray(selection.referenceIds)||new Set(selection.referenceIds).size!==selection.referenceIds.length)throw new Error('Duplicate or malformed standards selection.');
 const references=selection.referenceIds.map(id=>{const r=STANDARDS_REFERENCES.find(r=>r.id===id);if(!r)throw new Error(`Unknown standards reference: ${id}`);return {...r};});
 const editions=new Set<string>();for(const r of references){const family=r.id.replace(/-(?:\d{4}|\d(?:-\d{4})?)$/,'');if(editions.has(family))throw new Error('Select one governing edition per reference.');editions.add(family);}
 return {jurisdiction:'EG',references,issueReady:false,unresolved:['Egyptian HVAC/fire/energy code editions and project-specific adoption instruments are not verified.','International reference selection does not establish Egyptian legal adoption.','Selected normative clauses, addenda, amendments and numerical criteria require source evidence.','Existing sizing values are preliminary engineering presets, not edition-specific certification.']};
}
export function evaluateStandardsApplicability(profile:ReturnType<typeof resolveStandardsSelection>,project:{occupancy:'nonresidential'|'nontransient-residential'|'healthcare'|'unknown'}):{referenceId:string;applicable:boolean|null;reason:string}[] {
 return profile.references.map(r=>({referenceId:r.id,applicable:r.id.startsWith('ashrae-62.1')&&project.occupancy==='nontransient-residential'?false:project.occupancy==='unknown'?null:true,reason:r.applicability}));
}
